spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 18000 # 30 minutes
      use-key-prefix: true
      cache-null-values: false
    cache-names:
      - session-cache
sbr:
  service:
    cookie-config:
      http-only: true
      secure: true
      domain: sbr.com
      path: /
      trl-session-id: TLS-SESSION-ID
      user-cookie-name: X-USER-AUTHORIZATION
